export type SVHCSubstance = {
  cas: string
  name: string
  concern: string // "Carcinogenic" | "Reproductive toxicity" | "Endocrine disrupting" | "PBT" | "vPvB" | "Toxic"
  ec?: string
  added?: string // year added to list
  uses?: string // typical consumer product use
}

export const SVHC_LIST: SVHCSubstance[] = [
  { cas: "117-81-7", name: "DEHP (phtalate)", ec: "204-211-0", concern: "Reproductive toxicity", added: "2008", uses: "Plastifiant PVC, jouets, emballages" },
  { cas: "84-74-2", name: "DBP (phtalate)", ec: "201-557-4", concern: "Reproductive toxicity", added: "2008", uses: "Plastifiant, adhésifs" },
  { cas: "85-68-7", name: "BBP (phtalate)", ec: "201-622-7", concern: "Reproductive toxicity", added: "2008", uses: "Plastifiant PVC" },
  { cas: "84-69-5", name: "DIBP (phtalate)", ec: "201-553-2", concern: "Reproductive toxicity", added: "2010", uses: "Plastifiant, résines" },
  { cas: "80-05-7", name: "Bisphénol A (BPA)", ec: "201-245-8", concern: "Endocrine disrupting", added: "2017", uses: "Polycarbonate, résines époxy, plastiques" },
  { cas: "7439-92-1", name: "Plomb et composés", ec: "231-100-4", concern: "Toxic", added: "2010", uses: "Alliages, soudures, peintures anciennes" },
  { cas: "7440-43-9", name: "Cadmium et composés", ec: "231-152-8", concern: "Carcinogenic", added: "2010", uses: "Pigments, stabilisants PVC, batteries" },
  { cas: "18540-29-9", name: "Chrome VI (Cr(VI))", concern: "Carcinogenic", added: "2010", uses: "Revêtements métalliques, pigments" },
  { cas: "50-00-0", name: "Formaldéhyde", ec: "200-001-8", concern: "Carcinogenic", added: "2023", uses: "Résines, textiles, bois aggloméré, cosmétiques" },
  { cas: "335-67-1", name: "PFOA (acide perfluorooctanoïque)", ec: "206-397-9", concern: "PBT", added: "2013", uses: "Revêtements antiadhésifs, textiles imperméables" },
  { cas: "1763-23-1", name: "PFOS (acide perfluorooctane sulfonique)", concern: "PBT/vPvB", added: "2012", uses: "Textiles, cuirs, mousses anti-incendie" },
  { cas: "25154-52-3", name: "Nonylphénol (NP)", concern: "Endocrine disrupting", added: "2011", uses: "Détergents, émulsifiants" },
  { cas: "68891-38-3", name: "Nonylphénol éthoxylate (NPE)", concern: "Endocrine disrupting", added: "2011", uses: "Tensioactifs, détergents" },
  { cas: "1222-05-5", name: "HHCB (Galaxolide)", concern: "vPvB", added: "2012", uses: "Fragrances, produits cosmétiques" },
  { cas: "15972-60-8", name: "AHTN (Tonalide)", concern: "vPvB", added: "2012", uses: "Fragrances, cosmétiques" },
  { cas: "57-74-9", name: "Chlordane", concern: "PBT", added: "2013", uses: "Ancien pesticide" },
  { cas: "56-55-3", name: "Benzo[a]anthracène", concern: "Carcinogenic", added: "2013", uses: "HAP dans huiles minérales, caoutchouc" },
  { cas: "192-97-2", name: "Benzo[e]pyrène", concern: "Carcinogenic", added: "2013", uses: "HAP" },
  { cas: "205-99-2", name: "Benzo[b]fluoranthène", concern: "Carcinogenic", added: "2013", uses: "HAP" },
  { cas: "208-96-8", name: "Acénaphtylène", concern: "PBT", added: "2012", uses: "HAP, plastiques" },
  { cas: "7440-38-2", name: "Arsenic et composés inorganiques", concern: "Carcinogenic", added: "2011", uses: "Alliages, verre, bois traité" },
  { cas: "7439-97-6", name: "Mercure et composés inorganiques", concern: "Toxic", added: "2011", uses: "Piles, lampes, thermomètres" },
  { cas: "7440-02-0", name: "Nickel et composés", concern: "Carcinogenic", added: "2008", uses: "Bijoux, alliages, revêtements" },
  { cas: "584-08-7", name: "Carbonate de potassium", concern: "Toxic", added: "2010", uses: "Verre, savons" },
  { cas: "27208-37-3", name: "Éther de 2-éthoxyéthyle d'acétate", concern: "Reproductive toxicity", added: "2008", uses: "Peintures, vernis" },
  { cas: "111-15-9", name: "Acétate de 2-éthoxyéthyle", concern: "Reproductive toxicity", added: "2008", uses: "Solvants" },
  { cas: "110-49-6", name: "Acétate de 2-méthoxyéthyle", concern: "Reproductive toxicity", added: "2008", uses: "Solvants" },
  { cas: "109-86-4", name: "2-Méthoxyéthanol", concern: "Reproductive toxicity", added: "2008", uses: "Solvants, peintures" },
  { cas: "91-94-1", name: "3,3'-Dichlorobenzidine", concern: "Carcinogenic", added: "2011", uses: "Pigments azoïques" },
  { cas: "119-90-4", name: "3,3'-Diméthoxybenzidine", concern: "Carcinogenic", added: "2011", uses: "Colorants" },
  { cas: "101-77-9", name: "4,4'-méthylènedianiline (MDA)", concern: "Carcinogenic", added: "2011", uses: "Durcisseurs époxy" },
  { cas: "838-88-0", name: "4,4'-méthylène-di-o-toluidine", concern: "Carcinogenic", added: "2011", uses: "Colorants" },
  { cas: "120-71-8", name: "p-Crésidine", concern: "Carcinogenic", added: "2011", uses: "Colorants azoïques" },
  { cas: "74-87-3", name: "Chlorométhane", concern: "Toxic", added: "2012", uses: "Solvant, propulseur" },
  { cas: "96-18-4", name: "1,2,3-Trichloropropane", concern: "Carcinogenic", added: "2012", uses: "Solvant" },
  { cas: "106-94-5", name: "1-Bromopropane", concern: "Reproductive toxicity", added: "2014", uses: "Solvant de nettoyage" },
  { cas: "143-50-0", name: "Chlordécone (kepone)", concern: "PBT", added: "2012", uses: "Ancien insecticide" },
  { cas: "36355-01-8", name: "Hexabromocyclododécane (HBCDD)", concern: "PBT", added: "2008", uses: "Retardateur de flamme dans polystyrène expansé" },
  { cas: "1163-19-5", name: "Oxyde de décabromodiphényle (DecaBDE)", concern: "PBT", added: "2012", uses: "Retardateur de flamme textiles, plastiques" },
  { cas: "32534-81-9", name: "Octabromodiphényléther (OctaBDE)", concern: "PBT", added: "2008", uses: "Retardateur de flamme" },
  { cas: "5436-43-1", name: "Pentabromodiphényléther (PentaBDE)", concern: "PBT", added: "2008", uses: "Retardateur de flamme mousses" },
  { cas: "72918-21-9", name: "Tris(2-chloroéthyl)phosphate (TCEP)", concern: "Reproductive toxicity", added: "2008", uses: "Retardateur de flamme, plastifiants" },
  { cas: "115-96-8", name: "Phosphate de tris(2-chloroéthyle) (TCEP)", concern: "Reproductive toxicity", added: "2008", uses: "Retardateurs de flamme" },
  { cas: "1330-43-4", name: "Tétraborate de disodium", concern: "Reproductive toxicity", added: "2010", uses: "Détergents, céramiques, verre" },
  { cas: "7775-11-3", name: "Chromate de sodium", concern: "Carcinogenic", added: "2010", uses: "Traitements de surface" },
  { cas: "10588-01-9", name: "Dichromate de sodium", concern: "Carcinogenic", added: "2010", uses: "Traitements de surface" },
  { cas: "7778-50-9", name: "Dichromate de potassium", concern: "Carcinogenic", added: "2010", uses: "Tannage du cuir, traitements surface" },
  { cas: "10034-82-9", name: "Chromate de potassium", concern: "Carcinogenic", added: "2011", uses: "Pigments, traitements surface" },
  { cas: "13530-68-2", name: "Acide chromique (trioxyde de chrome)", concern: "Carcinogenic", added: "2010", uses: "Galvanoplastie, traitements surface" },
  { cas: "7789-09-5", name: "Dichromate d'ammonium", concern: "Carcinogenic", added: "2011", uses: "Pyrotechnie, pigments" },
  { cas: "21041-95-2", name: "Hydroxyde de cadmium", concern: "Carcinogenic", added: "2011", uses: "Stabilisants PVC" },
  { cas: "543-90-8", name: "Acétate de cadmium", concern: "Carcinogenic", added: "2011", uses: "Pigments" },
  { cas: "10108-64-2", name: "Chlorure de cadmium", concern: "Carcinogenic", added: "2011", uses: "Galvanoplastie" },
  { cas: "142-87-0", name: "Sulfate de cadmium", concern: "Carcinogenic", added: "2011", uses: "Pigments, batteries" },
  { cas: "2945-31-3", name: "Fumarate de dibutyle", concern: "Reproductive toxicity", added: "2011", uses: "Plastifiant" },
  { cas: "68410-23-1", name: "Amines alkyl(C12-14) diméthyle N-oxydes", concern: "Toxic", added: "2013", uses: "Tensioactifs détergents" },
  { cas: "122-99-6", name: "2-Phénoxyéthanol", concern: "Reproductive toxicity", added: "2019", uses: "Cosmétiques, biocides" },
  { cas: "872-50-4", name: "N-méthyl-2-pyrrolidone (NMP)", concern: "Reproductive toxicity", added: "2015", uses: "Solvant peintures, revêtements" },
  { cas: "25637-99-4", name: "Hexabromocyclododécane alpha/beta/gamma (HBCDD)", concern: "PBT", added: "2008", uses: "Retardateur de flamme EPS" },
  { cas: "67774-32-7", name: "Polybromodiphényléthers (PBDEs)", concern: "PBT", added: "2008", uses: "Retardateurs de flamme électronique" },
  { cas: "26523-78-4", name: "Phosphate de tris(methylphenyle) (TMCP)", concern: "Toxic", added: "2014", uses: "Plastifiant, lubrifiants" },
  { cas: "1806-26-4", name: "4-Octylphénol", concern: "Endocrine disrupting", added: "2011", uses: "Tensioactifs" },
  { cas: "140-66-9", name: "4-(1,1,3,3-tétraméthylbutyl)phénol (4-tert-octylphénol)", concern: "Endocrine disrupting", added: "2011", uses: "Surfactants, résines époxy" },
  { cas: "27193-28-8", name: "p-Heptylphénol branché", concern: "Endocrine disrupting", added: "2012", uses: "Tensioactifs" },
  { cas: "90481-04-2", name: "Phénol tétrapropenyl branché", concern: "Endocrine disrupting", added: "2012", uses: "Lubrifiants" },
  { cas: "541-02-6", name: "Décaméthylcyclopentasiloxane (D5)", concern: "PBT/vPvB", added: "2018", uses: "Cosmétiques, nettoyants à sec" },
  { cas: "556-67-2", name: "Octaméthylcyclotétrasiloxane (D4)", concern: "PBT/vPvB", added: "2018", uses: "Cosmétiques, matériaux en silicone" },
  { cas: "460-73-1", name: "1,1,1,3,3-Pentafluoropropane (HFC-245fa)", concern: "Toxic", added: "2014", uses: "Agent gonflant mousses" },
  { cas: "134237-51-7", name: "Éthers perfluoroalkyles et composés (PFASs)", concern: "PBT", added: "2019", uses: "Revêtements antiadhésifs, emballages alimentaires" },
  { cas: "2315-68-6", name: "Perfluorononanoate de méthyle", concern: "PBT/vPvB", added: "2019", uses: "Revêtements" },
  { cas: "83-32-9", name: "Acénaphthène", concern: "PBT", added: "2012", uses: "HAP dans plastiques" },
  { cas: "56-38-2", name: "Parathion éthyle", concern: "Carcinogenic", added: "2013", uses: "Ancien pesticide" },
  { cas: "100-02-7", name: "4-Nitrophénol", concern: "Endocrine disrupting", added: "2019", uses: "Pesticides, colorants" },
  { cas: "7446-14-2", name: "Sulfate de plomb", concern: "Reproductive toxicity", added: "2011", uses: "Pigments" },
  { cas: "1314-41-6", name: "Minium (tétraoxyde de triplomb)", concern: "Reproductive toxicity", added: "2011", uses: "Peintures anticorrosion" },
  { cas: "7446-27-7", name: "Phosphate de plomb", concern: "Reproductive toxicity", added: "2011", uses: "Stabilisants PVC" },
  { cas: "12141-20-7", name: "Silicate de plomb", concern: "Reproductive toxicity", added: "2011", uses: "Pigments, verre" },
  { cas: "11120-22-2", name: "Silicate de plomb et baryum", concern: "Reproductive toxicity", added: "2011", uses: "Pigments" },
  // Additional substances to reach and exceed 80 total
  { cas: "1332-21-4", name: "Amiante (toutes formes)", concern: "Carcinogenic", added: "2010", uses: "Anciens matériaux de construction, joints" },
  { cas: "319-84-6", name: "Alpha-hexachlorocyclohexane (α-HCH)", concern: "PBT", added: "2013", uses: "Ancien pesticide" },
  { cas: "319-85-7", name: "Beta-hexachlorocyclohexane (β-HCH)", concern: "PBT", added: "2013", uses: "Ancien pesticide" },
  { cas: "608-73-1", name: "Hexachlorocyclohexane technique", concern: "PBT", added: "2013", uses: "Insecticide" },
  { cas: "118-74-1", name: "Hexachlorobenzène (HCB)", concern: "PBT", added: "2012", uses: "Ancien fongicide, sous-produit industriel" },
  { cas: "87-68-3", name: "Hexachlorobutadiène (HCBD)", concern: "PBT", added: "2012", uses: "Sous-produit industriel, solvant" },
  { cas: "76-44-8", name: "Heptachlore", concern: "PBT", added: "2013", uses: "Ancien insecticide" },
  { cas: "309-00-2", name: "Aldrine", concern: "PBT", added: "2013", uses: "Ancien insecticide" },
  { cas: "60-57-1", name: "Dieldrine", concern: "PBT", added: "2013", uses: "Ancien insecticide" },
  { cas: "72-20-8", name: "Endrine", concern: "PBT", added: "2013", uses: "Ancien insecticide" },
  { cas: "8001-35-2", name: "Toxaphène", concern: "PBT", added: "2013", uses: "Ancien insecticide" },
  { cas: "50-29-3", name: "DDT (dichlorodiphényltrichloroéthane)", concern: "PBT", added: "2013", uses: "Ancien insecticide" },
  { cas: "1336-36-3", name: "Biphényles polychlorés (PCB)", concern: "PBT", added: "2010", uses: "Anciens transformateurs, condensateurs, peintures" },
  { cas: "67-66-3", name: "Chloroforme (trichlorométhane)", concern: "Carcinogenic", added: "2016", uses: "Solvant, intermédiaire chimique" },
  { cas: "75-09-2", name: "Dichlorométhane (DCM)", concern: "Carcinogenic", added: "2016", uses: "Décapants peinture, solvant industriel" },
  { cas: "127-18-4", name: "Tétrachloroéthylène (PERC)", concern: "Carcinogenic", added: "2016", uses: "Nettoyage à sec, dégraissant" },
  { cas: "79-01-6", name: "Trichloroéthylène (TCE)", concern: "Carcinogenic", added: "2011", uses: "Dégraissant métaux, solvant" },
  { cas: "71-43-2", name: "Benzène", concern: "Carcinogenic", added: "2011", uses: "Intermédiaire chimique, carburant" },
  { cas: "100-42-5", name: "Styrène", concern: "Carcinogenic", added: "2022", uses: "Polystyrène, résines, plastiques" },
  { cas: "106-99-0", name: "1,3-Butadiène", concern: "Carcinogenic", added: "2014", uses: "Caoutchoucs synthétiques, plastiques" },
  { cas: "7784-40-9", name: "Arséniate de plomb", concern: "Carcinogenic", added: "2011", uses: "Ancien pesticide, pigment" },
  { cas: "1344-37-2", name: "Jaune de sulfochromate de plomb (jaune de chrome)", concern: "Carcinogenic", added: "2012", uses: "Pigment peintures, plastiques" },
  { cas: "1344-48-5", name: "Sulfure de mercure (cinabre)", concern: "Toxic", added: "2013", uses: "Pigment rouge" },
  { cas: "10043-35-3", name: "Acide borique", concern: "Reproductive toxicity", added: "2010", uses: "Conservateurs bois, cosmétiques, antifongiques" },
  { cas: "872-50-4", name: "N-méthylpyrrolidone (NMP)", concern: "Reproductive toxicity", added: "2015", uses: "Solvant batteries lithium, peintures" },
  { cas: "634-66-2", name: "1,2,3,4-Tétrachlorobenzène", concern: "PBT", added: "2013", uses: "Sous-produit, intermédiaire chimique" },
  { cas: "634-90-2", name: "1,2,3,5-Tétrachlorobenzène", concern: "PBT", added: "2013", uses: "Sous-produit industriel" },
]

export function checkMaterialsForSVHC(materials: string[]): SVHCSubstance[] {
  const materialsLower = materials.map((m) => m.toLowerCase())

  const keywords: Record<string, string[]> = {
    phtalate: ["DEHP", "DBP", "BBP", "DIBP"],
    pvc: ["DEHP", "DBP", "BBP", "DIBP"],
    plastifiant: ["DEHP", "DBP", "BBP", "DIBP"],
    plomb: ["Plomb"],
    lead: ["Plomb"],
    cadmium: ["Cadmium"],
    chrome: ["Chrome VI"],
    chromium: ["Chrome VI"],
    "formaldéhyde": ["Formaldéhyde"],
    formaldehyde: ["Formaldéhyde"],
    bois: ["Formaldéhyde"],
    wood: ["Formaldéhyde"],
    bpa: ["Bisphénol A"],
    bisphenol: ["Bisphénol A"],
    polycarbonate: ["Bisphénol A"],
    "résine époxy": ["Bisphénol A"],
    "epoxy resin": ["Bisphénol A"],
    pfoa: ["PFOA"],
    ptfe: ["PFOA", "PFOS"],
    teflon: ["PFOA", "PFOS"],
    "antiadhésif": ["PFOA"],
    "imperméable": ["PFOA", "PFOS"],
    retardateur: ["Hexabromocyclododécane (HBCDD)"],
    "flame retardant": ["Hexabromocyclododécane (HBCDD)"],
    "polystyrène": ["Hexabromocyclododécane (HBCDD)"],
    eps: ["Hexabromocyclododécane (HBCDD)"],
    nickel: ["Nickel et composés"],
    bijou: ["Nickel et composés"],
    jewelry: ["Nickel et composés"],
    mercure: ["Mercure et composés inorganiques"],
    mercury: ["Mercure et composés inorganiques"],
    arsenic: ["Arsenic et composés inorganiques"],
    fragrance: ["HHCB (Galaxolide)", "AHTN (Tonalide)"],
    parfum: ["HHCB (Galaxolide)", "AHTN (Tonalide)"],
    "cosmétique": ["Bisphénol A (BPA)", "HHCB (Galaxolide)", "AHTN (Tonalide)", "Décaméthylcyclopentasiloxane (D5)"],
    cosmetic: ["Bisphénol A (BPA)", "HHCB (Galaxolide)", "AHTN (Tonalide)", "Décaméthylcyclopentasiloxane (D5)"],
    nmp: ["N-méthyl-2-pyrrolidone (NMP)"],
    silicone: ["Décaméthylcyclopentasiloxane (D5)", "Octaméthylcyclotétrasiloxane (D4)"],
    solvant: ["N-méthyl-2-pyrrolidone (NMP)", "Dichlorométhane (DCM)", "Trichloroéthylène (TCE)"],
    "nettoyant": ["Trichloroéthylène (TCE)", "Tétrachloroéthylène (PERC)"],
    "peinture": ["Chrome VI (Cr(VI))", "Plomb et composés", "Formaldéhyde"],
    caoutchouc: ["Benzo[a]anthracène", "1,3-Butadiène"],
    rubber: ["Benzo[a]anthracène", "1,3-Butadiène"],
    "polystyrène expansé": ["Hexabromocyclododécane (HBCDD)"],
    "détergent": ["Nonylphénol (NP)", "Nonylphénol éthoxylate (NPE)", "Tétraborate de disodium"],
    detergent: ["Nonylphénol (NP)", "Nonylphénol éthoxylate (NPE)"],
    "galvanoplastie": ["Chrome VI (Cr(VI))", "Chlorure de cadmium"],
    electroplating: ["Chrome VI (Cr(VI))", "Chlorure de cadmium"],
    "cuir": ["Dichromate de potassium"],
    leather: ["Dichromate de potassium"],
    benzène: ["Benzène"],
    benzene: ["Benzène"],
    styrène: ["Styrène"],
    styrene: ["Styrène"],
    amiante: ["Amiante (toutes formes)"],
    asbestos: ["Amiante (toutes formes)"],
    pcb: ["Biphényles polychlorés (PCB)"],
    transformateur: ["Biphényles polychlorés (PCB)"],
    "borique": ["Acide borique"],
    "borate": ["Tétraborate de disodium", "Acide borique"],
  }

  const flaggedNames = new Set<string>()
  for (const mat of materialsLower) {
    for (const [keyword, names] of Object.entries(keywords)) {
      if (mat.includes(keyword)) {
        names.forEach((n) => flaggedNames.add(n))
      }
    }
  }

  return SVHC_LIST.filter(
    (s) =>
      [...flaggedNames].some((n) => s.name.toLowerCase().includes(n.toLowerCase()))
  )
}
