"use client"
import { useState } from "react"
import { Plus, Bell, Loader2 } from "lucide-react"
import { useRouter } from "next/navigation"
import type { Locale } from "@/lib/i18n/locale"

interface Product { id:string; name:string; }
interface Props { products:Product[]; canAdd:boolean; locale:Locale }
const DICT={
 fr:{types:[['price_drop','Baisse de prix'],['price_increase','Hausse de prix'],['out_of_stock','Rupture de stock'],['back_in_stock','Retour en stock']],limit:'Limite atteinte — Upgrader',new:'Nouvelle alerte',title:'Être prévenu quand quelque chose compte',name:'Nom de l’alerte',namePh:'Ex. Prix trop bas',type:'Déclencheur',product:'Produit',threshold:'Variation minimale (%)',cancel:'Annuler',create:'Créer l’alerte',choose:'Choisissez le produit à surveiller.'},
 en:{types:[['price_drop','Price drop'],['price_increase','Price increase'],['out_of_stock','Out of stock'],['back_in_stock','Back in stock']],limit:'Limit reached — Upgrade',new:'New alert',title:'Get notified when something matters',name:'Alert name',namePh:'e.g. Price drops too far',type:'Trigger',product:'Product',threshold:'Minimum change (%)',cancel:'Cancel',create:'Create alert',choose:'Choose the product to monitor.'}
}
export function AddAlertButton({products,canAdd,locale}:Props){
 const t=DICT[locale]; const router=useRouter(); const [open,setOpen]=useState(false); const [name,setName]=useState(''); const [type,setType]=useState('price_drop'); const [productId,setProductId]=useState(products[0]?.id??''); const [threshold,setThreshold]=useState('5'); const [loading,setLoading]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();if(!productId)return;setLoading(true);try{const res=await fetch('/api/alerts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim()||`${t.types.find(x=>x[0]===type)?.[1]??type}`,type,productId,threshold:['price_drop','price_increase'].includes(type)?parseFloat(threshold)||5:null})});if(res.ok){setOpen(false);setName('');router.refresh()}}finally{setLoading(false)}}
 if(!canAdd)return <a href="/dashboard/billing" className="text-sm text-orange-400 border border-orange-400/30 px-4 py-2 rounded-xl">{t.limit}</a>
 if(products.length===0)return <button disabled className="flex items-center gap-2 text-sm text-gray-600 border border-white/10 px-4 py-2 rounded-xl"><Bell className="h-4 w-4"/> {t.new}</button>
 return <><button onClick={()=>setOpen(true)} className="flex items-center gap-2 bg-[#8B5CF6] hover:bg-[#7C3AED] text-white font-bold text-sm px-4 py-2 rounded-xl"><Plus className="h-4 w-4"/>{t.new}</button>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-4" onClick={()=>setOpen(false)}><div className="bg-[#0D0D14] border border-white/10 rounded-2xl p-6 w-full max-w-md" onClick={e=>e.stopPropagation()}><h2 className="font-bold text-white text-lg">{t.title}</h2><p className="text-xs text-gray-500 mt-1">{t.choose}</p><form onSubmit={submit} className="space-y-4 mt-5">
 <div><label className="block text-xs font-medium text-gray-400 mb-1.5">{t.name}</label><input value={name} onChange={e=>setName(e.target.value)} placeholder={t.namePh} className="w-full px-3 py-2.5 bg-white/5 border border-white/10 rounded-xl text-white text-sm"/></div>
 <div><label className="block text-xs font-medium text-gray-400 mb-1.5">{t.product}</label><select value={productId} onChange={e=>setProductId(e.target.value)} className="w-full px-3 py-2.5 bg-white/5 border border-white/10 rounded-xl text-white text-sm">{products.map(p=><option key={p.id} value={p.id} className="bg-[#0D0D14]">{p.name}</option>)}</select></div>
 <div><label className="block text-xs font-medium text-gray-400 mb-1.5">{t.type}</label><select value={type} onChange={e=>setType(e.target.value)} className="w-full px-3 py-2.5 bg-white/5 border border-white/10 rounded-xl text-white text-sm">{t.types.map(([v,l])=><option key={v} value={v} className="bg-[#0D0D14]">{l}</option>)}</select></div>
 {['price_drop','price_increase'].includes(type)&&<div><label className="block text-xs font-medium text-gray-400 mb-1.5">{t.threshold}</label><input type="number" min="1" max="100" step="0.5" value={threshold} onChange={e=>setThreshold(e.target.value)} className="w-full px-3 py-2.5 bg-white/5 border border-white/10 rounded-xl text-white text-sm"/></div>}
 <div className="flex gap-3 pt-2"><button type="button" onClick={()=>setOpen(false)} className="flex-1 py-2.5 bg-white/5 text-white text-sm rounded-xl">{t.cancel}</button><button type="submit" disabled={loading} className="flex-1 py-2.5 bg-[#8B5CF6] text-white font-bold text-sm rounded-xl flex items-center justify-center gap-2">{loading&&<Loader2 className="h-4 w-4 animate-spin"/>}{t.create}</button></div></form></div></div>}</>
}