import { NextResponse } from "next/server"
import { auth } from "@/auth"
import { getDb } from "@/lib/db"
import { organizations, organizationMembers, trackedCompetitors, trackedProducts } from "@/lib/db/schema"
import { eq, and, count } from "drizzle-orm"
import { z } from "zod"
import { scrapeAndApply, applyPriceResult } from "@/lib/scraping/apply"
import { withUnlimitedAccess } from "@/lib/admin"
const schema=z.object({url:z.string().url("URL invalide"),name:z.string().max(200).optional(),sku:z.string().max(100).optional(),price:z.number().positive().optional()})
const patchSchema=z.object({productId:z.string().min(1),price:z.number().positive().optional(),costPrice:z.number().nonnegative().nullable().optional(),yourPrice:z.number().nonnegative().nullable().optional()})
function hostOf(url:string){return new URL(url).hostname.toLowerCase().replace(/^www\./,'')}
function storeName(host:string){if(host.includes('amazon.'))return 'Amazon';if(host.includes('ebay.'))return 'eBay';if(host.includes('aliexpress.'))return 'AliExpress';if(host.includes('cdiscount.'))return 'Cdiscount';return host.split('.')[0].replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
export async function POST(req:Request){try{const s=await auth();if(!s?.user?.id)return NextResponse.json({error:'UNAUTHORIZED'},{status:401});const db=getDb();const [m]=await db.select({org:organizations}).from(organizationMembers).innerJoin(organizations,eq(organizationMembers.organizationId,organizations.id)).where(eq(organizationMembers.userId,s.user.id)).limit(1);if(!m)return NextResponse.json({error:'NO_ORG'},{status:404});const org=withUnlimitedAccess(m.org,s.user.email);const body=schema.parse(await req.json());const url=body.url.trim();const host=hostOf(url);const [{total}]=await db.select({total:count()}).from(trackedProducts).where(and(eq(trackedProducts.organizationId,org.id),eq(trackedProducts.isActive,true)));if(total>=org.productLimit)return NextResponse.json({error:'LIMIT_REACHED',limit:org.productLimit},{status:403});const [existing]=await db.select({id:trackedProducts.id}).from(trackedProducts).where(and(eq(trackedProducts.organizationId,org.id),eq(trackedProducts.url,url),eq(trackedProducts.isActive,true))).limit(1);if(existing)return NextResponse.json({error:'DUPLICATE_URL'},{status:409});let [source]=await db.select().from(trackedCompetitors).where(and(eq(trackedCompetitors.organizationId,org.id),eq(trackedCompetitors.domain,host),eq(trackedCompetitors.isActive,true))).limit(1);if(!source){[source]=await db.insert(trackedCompetitors).values({id:crypto.randomUUID(),organizationId:org.id,name:storeName(host),domain:host,platform:host.includes('amazon.')?'amazon':'custom',isActive:true}).returning()}const id=crypto.randomUUID();const [product]=await db.insert(trackedProducts).values({id,competitorId:source.id,organizationId:org.id,url,name:body.name||null,sku:body.sku||null,isActive:true}).returning();let finalProduct=product;let autoScraped=false;try{if(body.price!=null){await applyPriceResult({id,currentPrice:null},{price:body.price,currency:'EUR',inStock:null,name:body.name||null,confidence:'high'});autoScraped=false}else{const result=await scrapeAndApply({id,url,currentPrice:null});autoScraped=result.scraped}const [fresh]=await db.select().from(trackedProducts).where(eq(trackedProducts.id,id)).limit(1);if(fresh)finalProduct=fresh}catch(err){console.error('[products/POST] initial resolution failed',err)}return NextResponse.json({success:true,product:finalProduct,autoScraped,store:{name:source.name,domain:source.domain}})}catch(err){if(err instanceof z.ZodError)return NextResponse.json({error:'INVALID_INPUT',details:err.issues},{status:400});console.error('[products/POST]',err);return NextResponse.json({error:'SERVER_ERROR'},{status:500})}}
export async function PATCH(req:Request){try{const s=await auth();if(!s?.user?.id)return NextResponse.json({error:'UNAUTHORIZED'},{status:401});const db=getDb();const [m]=await db.select({org:organizations}).from(organizationMembers).innerJoin(organizations,eq(organizationMembers.organizationId,organizations.id)).where(eq(organizationMembers.userId,s.user.id)).limit(1);if(!m)return NextResponse.json({error:'NO_ORG'},{status:404});const b=patchSchema.parse(await req.json());const [p]=await db.select().from(trackedProducts).where(and(eq(trackedProducts.id,b.productId),eq(trackedProducts.organizationId,m.org.id))).limit(1);if(!p)return NextResponse.json({error:'NOT_FOUND'},{status:404});if(b.price!=null)await applyPriceResult({id:p.id,currentPrice:p.currentPrice},{price:b.price,currency:p.currency??'EUR',inStock:p.isInStock,name:null,confidence:'high'});if(b.costPrice!==undefined||b.yourPrice!==undefined)await db.update(trackedProducts).set({...b.costPrice!==undefined?{costPrice:b.costPrice}:{},...b.yourPrice!==undefined?{yourPrice:b.yourPrice}:{}}).where(eq(trackedProducts.id,b.productId));const [updated]=await db.select().from(trackedProducts).where(eq(trackedProducts.id,b.productId)).limit(1);return NextResponse.json({success:true,product:updated})}catch(err){if(err instanceof z.ZodError)return NextResponse.json({error:'INVALID_INPUT',details:err.issues},{status:400});console.error('[products/PATCH]',err);return NextResponse.json({error:'SERVER_ERROR'},{status:500})}}
export async function DELETE(req:Request){try{const s=await auth();if(!s?.user?.id)return NextResponse.json({error:'UNAUTHORIZED'},{status:401});const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'MISSING_ID'},{status:400});const db=getDb();const [m]=await db.select({org:organizations}).from(organizationMembers).innerJoin(organizations,eq(organizationMembers.organizationId,organizations.id)).where(eq(organizationMembers.userId,s.user.id)).limit(1);if(!m)return NextResponse.json({error:'NO_ORG'},{status:404});await db.update(trackedProducts).set({isActive:false}).where(and(eq(trackedProducts.id,id),eq(trackedProducts.organizationId,m.org.id)));return NextResponse.json({success:true})}catch(err){console.error('[products/DELETE]',err);return NextResponse.json({error:'SERVER_ERROR'},{status:500})}}
