"use client"

import Link from "next/link"
import { useState } from "react"
import { ArrowRight, Bell, Check, ChevronDown, LineChart, Radar, Sparkles, TrendingDown, TrendingUp, Zap } from "lucide-react"
import { ConforvaLogo } from "@/components/logo"

const faqs=[
 ["Est-ce que Conforva surveille tous les produits d'un site ?","Non. Vous choisissez exactement les fiches produits à surveiller. Si vous ajoutez un produit Amazon, Conforva surveille cette fiche précise — pas tout Amazon."],
 ["Que se passe-t-il quand un prix change ?","Conforva enregistre le nouveau prix, conserve l'historique et peut vous alerter pour que vous décidiez rapidement quoi faire."],
 ["Est-ce que je dois installer quelque chose ?","Non. Collez une URL produit et Conforva s'occupe de la collecte des données."],
 ["Puis-je suivre plusieurs boutiques ?","Oui. Vous pouvez suivre des produits provenant de plusieurs sites dans le même espace."],
]

function ProductPreview(){return <div className="relative"><div className="absolute -inset-8 bg-violet-500/10 blur-3xl"/><div className="relative rounded-2xl border border-white/10 bg-[#0D0E14] shadow-2xl overflow-hidden"><div className="h-10 border-b border-white/8 flex items-center gap-2 px-4"><span className="h-2.5 w-2.5 rounded-full bg-white/15"/><span className="h-2.5 w-2.5 rounded-full bg-white/15"/><span className="h-2.5 w-2.5 rounded-full bg-white/15"/><span className="ml-4 text-[10px] text-gray-600">app.conforva.com/products</span></div><div className="p-5"><div className="flex items-center justify-between mb-5"><div><p className="text-[10px] text-gray-500 uppercase tracking-widest">Market position</p><p className="text-lg font-bold text-white mt-1">Your monitored products</p></div><span className="text-[10px] text-emerald-400 bg-emerald-500/10 border border-emerald-500/15 rounded-full px-2.5 py-1">Monitoring active</span></div><div className="grid grid-cols-3 gap-3 mb-4">{[["Products","24"],["Price changes","7"],["Opportunities","3"]].map(([a,b])=><div key={a} className="rounded-xl bg-white/4 border border-white/6 p-3"><p className="text-[9px] text-gray-500">{a}</p><p className="text-xl font-black text-white mt-1">{b}</p></div>)}</div><div className="rounded-xl border border-white/7 overflow-hidden"><div className="grid grid-cols-12 px-3 py-2 border-b border-white/6 text-[9px] text-gray-600"><span className="col-span-5">PRODUCT</span><span className="col-span-2">STORE</span><span className="col-span-2 text-right">MARKET</span><span className="col-span-3 text-right">CHANGE</span></div>{[["Nike Air Max 270","Amazon","109€","-15%","down"],["Sony WH-1000XM5","Fnac","279€","-20%","down"],["Dyson V15","Darty","749€","+7%","up"]].map(([p,s,pr,ch,d])=><div key={p} className="grid grid-cols-12 px-3 py-3 border-b border-white/5 text-[10px] items-center"><span className="col-span-5 text-gray-200 font-medium truncate">{p}</span><span className="col-span-2 text-gray-500 truncate">{s}</span><span className="col-span-2 text-right text-white font-semibold">{pr}</span><span className={`col-span-3 text-right font-bold ${d==='down'?'text-emerald-400':'text-red-400'}`}>{d==='down'?<TrendingDown className="inline h-3 w-3 mr-1"/>:<TrendingUp className="inline h-3 w-3 mr-1"/>}{ch}</span></div>)}</div></div></div></div>}

export default function HomeClientV2(){const [open,setOpen]=useState<number|null>(null);return <main className="min-h-screen bg-[#08090C] text-white overflow-hidden">
<header className="fixed top-0 inset-x-0 z-50 bg-[#08090C]/85 backdrop-blur-xl border-b border-white/6"><div className="max-w-6xl mx-auto h-16 px-5 flex items-center justify-between"><Link href="/" className="flex items-center gap-2.5"><ConforvaLogo size={28}/><span className="font-black tracking-tight">CONFORVA</span></Link><nav className="hidden md:flex items-center gap-7 text-sm text-gray-400"><a href="#produit" className="hover:text-white">Le produit</a><a href="#fonctionnement" className="hover:text-white">Comment ça marche</a><a href="#tarifs" className="hover:text-white">Tarifs</a><a href="#faq" className="hover:text-white">FAQ</a></nav><div className="flex items-center gap-3"><Link href="/auth/login" className="hidden sm:block text-sm text-gray-400 hover:text-white">Connexion</Link><Link href="/auth/register" className="inline-flex items-center gap-2 bg-white text-black hover:bg-gray-200 font-bold text-sm px-4 py-2.5 rounded-xl">Commencer <ArrowRight className="h-4 w-4"/></Link></div></div></header>
<section className="pt-32 pb-20 px-5"><div className="max-w-6xl mx-auto grid lg:grid-cols-2 gap-14 items-center"><div><div className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/5 px-3 py-1.5 text-xs text-violet-200 mb-6"><span className="h-1.5 w-1.5 rounded-full bg-violet-400"/> Intelligence prix pour e-commerce</div><h1 className="text-5xl md:text-6xl font-black tracking-[-0.045em] leading-[1.02]">Arrêtez de deviner.<br/><span className="text-violet-300">Sachez quand agir.</span></h1><p className="text-lg md:text-xl text-gray-400 leading-relaxed mt-6 max-w-xl">Conforva surveille les <strong className="text-gray-200">produits qui comptent pour vous</strong>, détecte les changements de prix et de disponibilité, puis transforme ces données en décisions exploitables.</p><div className="flex flex-col sm:flex-row gap-3 mt-8"><Link href="/auth/register" className="inline-flex items-center justify-center gap-2 bg-[#8B5CF6] hover:bg-[#7C3AED] px-5 py-3.5 rounded-xl font-bold">Essayer gratuitement <ArrowRight className="h-4 w-4"/></Link><a href="#produit" className="inline-flex items-center justify-center px-5 py-3.5 rounded-xl border border-white/10 bg-white/4 text-gray-300 hover:text-white">Voir le produit</a></div><p className="text-xs text-gray-600 mt-4">Aucune carte bancaire nécessaire pour commencer.</p></div><ProductPreview/></div></section>
<section className="border-y border-white/6 bg-white/[0.015] py-5"><div className="max-w-6xl mx-auto px-5 grid sm:grid-cols-3 gap-5 text-sm"><div className="flex gap-3 items-center"><Radar className="h-5 w-5 text-violet-300"/><span className="text-gray-400">Surveillance produit par produit</span></div><div className="flex gap-3 items-center"><Bell className="h-5 w-5 text-violet-300"/><span className="text-gray-400">Alertes sur les changements importants</span></div><div className="flex gap-3 items-center"><Sparkles className="h-5 w-5 text-violet-300"/><span className="text-gray-400">Analyse IA pour prioriser les actions</span></div></div></section>
<section id="produit" className="py-24 px-5"><div className="max-w-6xl mx-auto"><div className="max-w-2xl mb-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Le produit</p><h2 className="text-4xl md:text-5xl font-black tracking-tight mt-3">Pas un tableau de bord de plus.</h2><p className="text-gray-400 text-lg mt-4">Un système qui transforme la surveillance concurrentielle en avantage opérationnel.</p></div><div className="grid md:grid-cols-3 gap-4">{[[LineChart,"Voir le marché","Prix actuel, historique, variations et positionnement pour chaque produit surveillé."],[Zap,"Repérer les opportunités","Identifiez les baisses, hausses et ruptures qui peuvent affecter vos ventes."],[Sparkles,"Décider avec l'IA","Conforva synthétise les signaux et vous aide à savoir quelles situations méritent votre attention."]].map(([Icon,title,desc])=>{const I=Icon as any;return <div key={title as string} className="rounded-2xl border border-white/8 bg-white/[0.025] p-7"><div className="h-10 w-10 rounded-xl bg-violet-500/10 border border-violet-400/15 flex items-center justify-center"><I className="h-5 w-5 text-violet-300"/></div><h3 className="text-lg font-bold mt-5">{title as string}</h3><p className="text-sm text-gray-500 leading-relaxed mt-2">{desc as string}</p></div>})}</div></div></section>
<section id="fonctionnement" className="py-24 px-5 bg-white/[0.015] border-y border-white/6"><div className="max-w-5xl mx-auto"><div className="text-center max-w-2xl mx-auto"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Simple à mettre en place</p><h2 className="text-4xl font-black mt-3">Vous donnez les produits. Conforva fait le reste.</h2></div><div className="grid md:grid-cols-3 gap-5 mt-12">{[["01","Collez une URL","Ajoutez l'URL exacte d'une fiche produit — Amazon, Shopify, WooCommerce ou autre site compatible."],["02","Conforva surveille","Le prix, la disponibilité et l'historique sont suivis automatiquement selon votre fréquence."],["03","Vous agissez","Recevez les alertes utiles et utilisez les analyses pour décider quoi faire." ]].map(([n,t,d])=><div key={n} className="relative rounded-2xl border border-white/8 bg-[#0B0C11] p-6"><span className="text-xs font-black text-violet-300">{n}</span><h3 className="font-bold text-lg mt-8">{t}</h3><p className="text-sm text-gray-500 leading-relaxed mt-2">{d}</p></div>)}</div></div></section>
<section id="tarifs" className="py-24 px-5"><div className="max-w-5xl mx-auto text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Tarifs</p><h2 className="text-4xl font-black mt-3">Commencez petit. Passez à l'échelle quand ça compte.</h2><p className="text-gray-500 mt-4">Votre abonnement dépend du nombre de produits que vous voulez réellement surveiller.</p><div className="grid md:grid-cols-3 gap-4 text-left mt-12">{[["Starter","Pour tester le workflow","Produit-first","Historique","Alertes"],["Growth","Pour une vraie activité e-commerce","Plus de produits","Rapports IA","Fréquence supérieure"],["Pro","Pour piloter un catalogue important","Catalogue étendu","Analyse avancée","Priorité de surveillance"]].map(([name,desc,...features],i)=><div key={name} className={`rounded-2xl border p-6 ${i===1?'border-violet-400/30 bg-violet-500/[0.06]':'border-white/8 bg-white/[0.025]'}`}><p className="text-lg font-bold">{name}</p><p className="text-sm text-gray-500 mt-2 min-h-10">{desc}</p><div className="space-y-2 mt-6">{features.map(f=><p key={f} className="text-sm text-gray-300"><Check className="inline h-4 w-4 text-violet-300 mr-2"/>{f}</p>)}</div><Link href="/auth/register" className="mt-7 block text-center py-3 rounded-xl bg-white/8 hover:bg-white/12 text-sm font-bold">Commencer</Link></div>)}</div></div></section>
<section id="faq" className="py-24 px-5 bg-white/[0.015] border-y border-white/6"><div className="max-w-3xl mx-auto"><h2 className="text-4xl font-black text-center">Questions fréquentes</h2><div className="mt-10 space-y-2">{faqs.map(([q,a],i)=><div key={q} className="border border-white/8 rounded-xl bg-white/[0.02] overflow-hidden"><button onClick={()=>setOpen(open===i?null:i)} className="w-full flex items-center justify-between p-5 text-left font-semibold">{q}<ChevronDown className={`h-4 w-4 text-gray-500 transition-transform ${open===i?'rotate-180':''}`}/></button>{open===i&&<p className="px-5 pb-5 text-sm text-gray-500 leading-relaxed">{a}</p>}</div>)}</div></div></section>
<footer className="py-10 px-5"><div className="max-w-6xl mx-auto flex flex-col sm:flex-row justify-between gap-5 text-xs text-gray-600"><span>© {new Date().getFullYear()} Conforva</span><div className="flex gap-5"><Link href="/privacy">Confidentialité</Link><Link href="/cgv">CGV</Link><Link href="/contact">Contact</Link></div></div></footer>
</main>}
