"use client"

import Link from "next/link"
import { useState } from "react"
import { ArrowRight, Bell, Check, ChevronDown, ExternalLink, Package, TrendingDown, TrendingUp, Zap } from "lucide-react"
import { ConforvaLogo } from "@/components/logo"

const changes=[
 {store:"Amazon",name:"Sony WH-1000XM5",from:"349 €",to:"299 €",pct:"-14.3%",down:true},
 {store:"Fnac",name:"MacBook Air",from:"1 199 €",to:"1 099 €",pct:"-8.3%",down:true},
 {store:"Darty",name:"Dyson V15",from:"649 €",to:"699 €",pct:"+7.7%",down:false},
]

export default function HomeClient(){
 const [open,setOpen]=useState<number|null>(null)
 return <main className="min-h-screen bg-[#08090C] text-white overflow-hidden">
  <nav className="max-w-6xl mx-auto px-5 h-18 flex items-center justify-between border-b border-white/7">
   <Link href="/" className="flex items-center gap-2.5"><ConforvaLogo size={29}/><span className="font-black tracking-tight">CONFORVA</span></Link>
   <div className="hidden md:flex items-center gap-7 text-sm text-gray-500"><a href="#produit" className="hover:text-white">Le produit</a><a href="#comment" className="hover:text-white">Comment ça marche</a><a href="#tarifs" className="hover:text-white">Tarifs</a><Link href="/blog" className="hover:text-white">Ressources</Link></div>
   <div className="flex items-center gap-2"><Link href="/auth/login" className="hidden sm:block text-sm text-gray-400 px-3 py-2 hover:text-white">Connexion</Link><Link href="/auth/register" className="bg-white text-black font-bold text-sm px-4 py-2.5 rounded-xl hover:bg-gray-200 transition-colors">Commencer</Link></div>
  </nav>

  <section className="max-w-6xl mx-auto px-5 pt-20 md:pt-28 pb-20">
   <div className="max-w-4xl">
    <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.035] px-3 py-1.5 text-xs text-gray-400"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/> Veille e-commerce automatisée</div>
    <h1 className="text-5xl md:text-7xl font-black tracking-[-0.055em] leading-[0.98] mt-6">Votre marché change.<br/><span className="text-gray-500">Vous devez le savoir.</span></h1>
    <p className="text-lg md:text-xl text-gray-400 leading-8 max-w-2xl mt-7">Conforva surveille les produits qui comptent pour votre boutique, détecte les changements de prix et de disponibilité, et vous indique les mouvements qui méritent votre attention.</p>
    <div className="flex flex-col sm:flex-row gap-3 mt-9"><Link href="/auth/register" className="inline-flex items-center justify-center gap-2 bg-[#8B5CF6] hover:bg-[#7C3AED] px-6 py-3.5 rounded-xl font-bold transition-colors">Surveiller mon premier produit <ArrowRight className="h-4 w-4"/></Link><a href="#produit" className="inline-flex items-center justify-center px-6 py-3.5 rounded-xl border border-white/10 text-gray-300 hover:text-white hover:bg-white/5">Voir comment ça marche</a></div>
    <div className="flex flex-wrap gap-x-6 gap-y-2 mt-6 text-xs text-gray-600"><span>✓ Aucune configuration de concurrent</span><span>✓ Une URL suffit</span><span>✓ Annulable à tout moment</span></div>
   </div>

   <div id="produit" className="mt-20 md:mt-28 rounded-3xl border border-white/9 bg-[#0D0E13] overflow-hidden shadow-2xl">
    <div className="px-5 md:px-7 py-4 border-b border-white/7 flex items-center justify-between"><div><p className="text-xs font-bold text-white">Conforva / Décisions</p><p className="text-[11px] text-gray-600 mt-0.5">Ce qui mérite votre attention aujourd'hui</p></div><span className="inline-flex items-center gap-1.5 text-[11px] text-emerald-400"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse"/> Surveillance active</span></div>
    <div className="p-4 md:p-7 grid lg:grid-cols-[1.2fr_.8fr] gap-4">
     <div className="rounded-2xl border border-white/7 bg-black/20 overflow-hidden"><div className="px-5 py-4 border-b border-white/7 flex justify-between"><span className="text-xs font-semibold text-gray-300">Mouvements détectés</span><span className="text-[11px] text-gray-600">Dernières 24h</span></div>{changes.map((x)=><div key={x.name} className="px-5 py-4 border-b border-white/5 last:border-0 flex items-center gap-4"><div className={`h-9 w-9 rounded-xl flex items-center justify-center ${x.down?"bg-emerald-500/10":"bg-red-500/10"}`}>{x.down?<TrendingDown className="h-4 w-4 text-emerald-400"/>:<TrendingUp className="h-4 w-4 text-red-400"/>}</div><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-white truncate">{x.name}</p><p className="text-[11px] text-gray-600">{x.store} · {x.from} → {x.to}</p></div><span className={`text-xs font-bold ${x.down?"text-emerald-400":"text-red-400"}`}>{x.pct}</span></div>)}</div>
     <div className="rounded-2xl border border-[#8B5CF6]/20 bg-[#8B5CF6]/[0.055] p-5 md:p-6"><div className="flex items-center gap-2 text-xs font-bold text-[#C4B5FD]"><Zap className="h-4 w-4"/> Recommandation</div><h3 className="text-xl font-black mt-4">Votre prix est maintenant au-dessus du marché.</h3><p className="text-sm text-gray-400 mt-3 leading-6">Le produit suivi vient de baisser de 14,3 %. Conforva vous signale le mouvement avant qu'il passe inaperçu.</p><div className="mt-6 rounded-xl bg-black/20 border border-white/7 p-4"><p className="text-[11px] text-gray-600 uppercase tracking-wider">Action à envisager</p><p className="text-sm font-bold text-white mt-1">Vérifier votre positionnement prix</p><p className="text-xs text-gray-600 mt-1">Aucune modification automatique de votre boutique.</p></div></div>
    </div>
   </div>
  </section>

  <section id="comment" className="border-y border-white/7 bg-white/[0.018]"><div className="max-w-6xl mx-auto px-5 py-20 md:py-24"><div className="max-w-2xl"><p className="text-xs uppercase tracking-[0.18em] text-[#A78BFA] font-bold">Simple par conception</p><h2 className="text-3xl md:text-5xl font-black tracking-[-0.04em] mt-3">Vous choisissez les produits.<br/>Conforva surveille le reste.</h2></div><div className="grid md:grid-cols-3 gap-4 mt-12">{[["01","Collez une URL","Ajoutez la page exacte d'un produit concurrent. Pas besoin de configurer tout son catalogue."],["02","Conforva observe","Prix, disponibilité et évolutions sont suivis automatiquement selon la fréquence de votre plan."],["03","Vous décidez","Recevez les changements importants et utilisez-les pour ajuster votre stratégie." ]].map(([n,t,d])=><div key={n} className="rounded-2xl border border-white/8 bg-[#0C0D12] p-6"><span className="text-xs font-mono text-[#A78BFA]">{n}</span><h3 className="text-lg font-bold mt-8">{t}</h3><p className="text-sm text-gray-500 leading-6 mt-2">{d}</p></div>)}</div></div></section>

  <section className="max-w-6xl mx-auto px-5 py-20 md:py-24"><div className="grid lg:grid-cols-2 gap-12 items-start"><div><p className="text-xs uppercase tracking-[0.18em] text-[#A78BFA] font-bold">Pourquoi payer pour ça ?</p><h2 className="text-3xl md:text-5xl font-black tracking-[-0.04em] mt-3">Parce que regarder vos concurrents à la main n'est pas une stratégie.</h2><p className="text-gray-500 leading-7 mt-5 max-w-xl">Un changement de prix peut durer quelques heures. Une rupture peut créer une opportunité. Conforva transforme cette veille répétitive en un flux d'informations exploitable.</p></div><div className="space-y-3">{[["Alertes utiles","Pas de flux interminable : concentrez-vous sur les mouvements qui comptent."],["Historique","Comprenez si une baisse est exceptionnelle ou si elle s'inscrit dans une tendance."],["Disponibilité","Détectez les ruptures et retours en stock de produits surveillés."],["Décision","Chaque signal doit vous aider à savoir quoi regarder ensuite."]].map(([t,d])=><div key={t} className="rounded-2xl border border-white/8 bg-white/[0.025] p-5 flex gap-4"><div className="h-9 w-9 shrink-0 rounded-xl bg-white/5 flex items-center justify-center"><Check className="h-4 w-4 text-[#A78BFA]"/></div><div><h3 className="text-sm font-bold">{t}</h3><p className="text-xs text-gray-500 leading-5 mt-1">{d}</p></div></div>)}</div></div></section>

  <section id="tarifs" className="border-t border-white/7 bg-white/[0.018]"><div className="max-w-6xl mx-auto px-5 py-20 md:py-24"><div className="text-center max-w-2xl mx-auto"><p className="text-xs uppercase tracking-[0.18em] text-[#A78BFA] font-bold">Tarifs</p><h2 className="text-3xl md:text-5xl font-black tracking-[-0.04em] mt-3">Commencez petit. Augmentez quand Conforva devient indispensable.</h2><p className="text-sm text-gray-500 mt-4">Pas de contrat annuel imposé. Vous payez pour le nombre de produits réellement surveillés.</p></div><div className="grid md:grid-cols-3 gap-4 mt-12">{[["Starter","19 €","100 produits","Surveillance quotidienne"],["Growth","49 €","500 produits","Surveillance plusieurs fois par jour"],["Pro","99 €","5 000 produits","Surveillance horaire + rapports IA"]].map(([name,price,limit,freq],i)=><div key={name} className={`rounded-2xl border p-6 ${i===1?"border-[#8B5CF6]/40 bg-[#8B5CF6]/[0.055]":"border-white/8 bg-[#0C0D12]"}`}><div className="flex justify-between items-center"><h3 className="font-bold">{name}</h3>{i===1&&<span className="text-[10px] uppercase tracking-wider font-bold text-[#C4B5FD]">Le plus choisi</span>}</div><p className="text-4xl font-black mt-7">{price}<span className="text-sm text-gray-600 font-normal"> / mois</span></p><div className="mt-6 space-y-3 text-sm text-gray-400"><p className="flex gap-2"><Check className="h-4 w-4 text-emerald-400"/>{limit}</p><p className="flex gap-2"><Check className="h-4 w-4 text-emerald-400"/>{freq}</p><p className="flex gap-2"><Check className="h-4 w-4 text-emerald-400"/>Alertes de changement</p></div><Link href="/auth/register" className={`mt-8 w-full inline-flex justify-center py-3 rounded-xl font-bold text-sm ${i===1?"bg-[#8B5CF6] hover:bg-[#7C3AED]":"bg-white/7 hover:bg-white/10"}`}>Commencer</Link></div>)}</div></div></section>

  <section className="max-w-4xl mx-auto px-5 py-20"><div className="rounded-3xl border border-white/8 bg-[#0D0E13] p-7 md:p-10 text-center"><Bell className="h-6 w-6 text-[#A78BFA] mx-auto"/><h2 className="text-3xl md:text-4xl font-black tracking-[-0.04em] mt-4">Ne découvrez plus les changements trop tard.</h2><p className="text-gray-500 mt-3">Ajoutez votre premier produit et voyez immédiatement ce que Conforva peut surveiller.</p><Link href="/auth/register" className="inline-flex items-center gap-2 mt-7 bg-white text-black px-6 py-3.5 rounded-xl font-bold hover:bg-gray-200">Commencer gratuitement <ArrowRight className="h-4 w-4"/></Link></div></section>

  <footer className="border-t border-white/7"><div className="max-w-6xl mx-auto px-5 py-8 flex flex-col md:flex-row items-center justify-between gap-4"><div className="flex items-center gap-2"><ConforvaLogo size={22}/><span className="text-sm font-bold">CONFORVA</span></div><p className="text-xs text-gray-600">Intelligence concurrentielle pour e-commerce.</p><div className="flex gap-4 text-xs text-gray-600"><Link href="/privacy" className="hover:text-white">Confidentialité</Link><Link href="/cgv" className="hover:text-white">CGV</Link><Link href="/contact" className="hover:text-white">Contact</Link></div></div></footer>
 </main>
}
