import { NextResponse } from "next/server"
import { auth } from "@/auth"
import { getDb } from "@/lib/db"
import { organizations, organizationMembers, alerts, trackedProducts } from "@/lib/db/schema"
import { eq, and, count } from "drizzle-orm"
import { z } from "zod"
import { withUnlimitedAccess } from "@/lib/admin"

const schema=z.object({name:z.string().min(1).max(100),type:z.enum(["price_drop","price_increase","out_of_stock","back_in_stock"]),productId:z.string().min(1),threshold:z.number().nullable().optional()})
async function getOrg(){const session=await auth();if(!session?.user?.id)return null;const db=getDb();const [m]=await db.select({org:organizations}).from(organizationMembers).innerJoin(organizations,eq(organizationMembers.organizationId,organizations.id)).where(eq(organizationMembers.userId,session.user.id)).limit(1);return m?withUnlimitedAccess(m.org,session.user.email):null}
export async function POST(req:Request){try{const org=await getOrg();if(!org)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const db=getDb();const body=schema.parse(await req.json());const [n]=await db.select({c:count()}).from(alerts).where(and(eq(alerts.organizationId,org.id),eq(alerts.isActive,true)));if((n?.c??0)>=org.alertLimit)return NextResponse.json({error:"LIMIT_REACHED"},{status:403});const [product]=await db.select({id:trackedProducts.id}).from(trackedProducts).where(and(eq(trackedProducts.id,body.productId),eq(trackedProducts.organizationId,org.id),eq(trackedProducts.isActive,true))).limit(1);if(!product)return NextResponse.json({error:"PRODUCT_NOT_FOUND"},{status:404});const [alert]=await db.insert(alerts).values({organizationId:org.id,name:body.name,type:body.type,productId:body.productId,competitorId:null,threshold:body.threshold??null,isActive:true,emailNotification:true}).returning();return NextResponse.json({success:true,alert})}catch(err){if(err instanceof z.ZodError)return NextResponse.json({error:"INVALID_INPUT"},{status:400});console.error('[alerts/POST]',err);return NextResponse.json({error:"SERVER_ERROR"},{status:500})}}
export async function DELETE(req:Request){try{const org=await getOrg();if(!org)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:"MISSING_ID"},{status:400});const db=getDb();await db.delete(alerts).where(and(eq(alerts.id,id),eq(alerts.organizationId,org.id)));return NextResponse.json({success:true})}catch(err){console.error('[alerts/DELETE]',err);return NextResponse.json({error:"SERVER_ERROR"},{status:500})}}
